var searchData=
[
  ['make_5fsample_5fvirus_5fneighbors_40',['make_sample_virus_neighbors',['../namespacesampler.html#a4cafc444e0a6c563f34ed5f9b5366ae4',1,'sampler::make_sample_virus_neighbors()'],['../namespaceepiworld_1_1sampler.html#a058e471163798e71719e9580b016692f',1,'epiworld::sampler::make_sample_virus_neighbors()']]],
  ['make_5fupdate_5fsusceptible_41',['make_update_susceptible',['../namespacesampler.html#a9f4c303b5e9016b050dd008fec902448',1,'sampler::make_update_susceptible()'],['../namespaceepiworld_1_1sampler.html#af58114de37befaa5de5450e3d4414b22',1,'epiworld::sampler::make_update_susceptible()']]],
  ['mit_20license_42',['MIT License',['../md__l_i_c_e_n_s_e.html',1,'']]],
  ['model_43',['Model',['../classepiworld_1_1_model.html',1,'epiworld::Model&lt; TSeq &gt;'],['../class_model.html',1,'Model&lt; TSeq &gt;']]],
  ['model1_44',['model1',['../md_model1.html',1,'']]],
  ['model_3c_20epi_5fdefault_5ftseq_20_3e_45',['Model&lt; EPI_DEFAULT_TSEQ &gt;',['../classepiworld_1_1_model.html',1,'epiworld']]],
  ['model_3c_20int_20_3e_46',['Model&lt; int &gt;',['../classepiworld_1_1_model.html',1,'epiworld']]],
  ['modeldiffnet_47',['ModelDiffNet',['../classepiworld_1_1epimodels_1_1_model_diff_net.html',1,'epiworld::epimodels::ModelDiffNet&lt; TSeq &gt;'],['../class_model_diff_net.html',1,'ModelDiffNet&lt; TSeq &gt;']]],
  ['modelseir_48',['ModelSEIR',['../classepiworld_1_1epimodels_1_1_model_s_e_i_r.html',1,'epiworld::epimodels::ModelSEIR&lt; TSeq &gt;'],['../class_model_s_e_i_r.html',1,'ModelSEIR&lt; TSeq &gt;']]],
  ['modelseirconn_49',['ModelSEIRCONN',['../classepiworld_1_1epimodels_1_1_model_s_e_i_r_c_o_n_n.html',1,'epiworld::epimodels::ModelSEIRCONN&lt; TSeq &gt;'],['../classepiworld_1_1epimodels_1_1_model_s_e_i_r_c_o_n_n.html#a30438ed783cd6ad854885b016209bc44',1,'epiworld::epimodels::ModelSEIRCONN::ModelSEIRCONN()'],['../class_model_s_e_i_r_c_o_n_n.html#a30438ed783cd6ad854885b016209bc44',1,'ModelSEIRCONN::ModelSEIRCONN()'],['../class_model_s_e_i_r_c_o_n_n.html',1,'ModelSEIRCONN&lt; TSeq &gt;']]],
  ['modelseird_50',['ModelSEIRD',['../classepiworld_1_1epimodels_1_1_model_s_e_i_r_d.html',1,'epiworld::epimodels::ModelSEIRD&lt; TSeq &gt;'],['../class_model_s_e_i_r_d.html#a903d3167f93a680ee78c920792496ab7',1,'ModelSEIRD::ModelSEIRD()'],['../class_model_s_e_i_r_d.html',1,'ModelSEIRD&lt; TSeq &gt;'],['../class_model_s_e_i_r_d.html#aa3cab7da0ed59f7b3cfb3c7494397a01',1,'ModelSEIRD::ModelSEIRD()'],['../classepiworld_1_1epimodels_1_1_model_s_e_i_r_d.html#a903d3167f93a680ee78c920792496ab7',1,'epiworld::epimodels::ModelSEIRD::ModelSEIRD(std::string vname, epiworld_double prevalence, epiworld_double transmission_rate, epiworld_double avg_incubation_days, epiworld_double recovery_rate, epiworld_double death_rate)'],['../classepiworld_1_1epimodels_1_1_model_s_e_i_r_d.html#aa3cab7da0ed59f7b3cfb3c7494397a01',1,'epiworld::epimodels::ModelSEIRD::ModelSEIRD(ModelSEIRD&lt; TSeq &gt; &amp;model, std::string vname, epiworld_double prevalence, epiworld_double transmission_rate, epiworld_double avg_incubation_days, epiworld_double recovery_rate, epiworld_double death_rate)']]],
  ['modelseirdconn_51',['ModelSEIRDCONN',['../classepiworld_1_1epimodels_1_1_model_s_e_i_r_d_c_o_n_n.html',1,'epiworld::epimodels::ModelSEIRDCONN&lt; TSeq &gt;'],['../class_model_s_e_i_r_d_c_o_n_n.html',1,'ModelSEIRDCONN&lt; TSeq &gt;'],['../class_model_s_e_i_r_d_c_o_n_n.html#add01e207658b9de4f98d33a658d14987',1,'ModelSEIRDCONN::ModelSEIRDCONN()'],['../classepiworld_1_1epimodels_1_1_model_s_e_i_r_d_c_o_n_n.html#add01e207658b9de4f98d33a658d14987',1,'epiworld::epimodels::ModelSEIRDCONN::ModelSEIRDCONN()']]],
  ['modelseirentitiesconn_52',['ModelSEIREntitiesConn',['../class_model_s_e_i_r_entities_conn.html',1,'ModelSEIREntitiesConn&lt; TSeq &gt;'],['../class_model_s_e_i_r_entities_conn.html#a3eaf92d2e617a30b43ded0f5d0ebbf04',1,'ModelSEIREntitiesConn::ModelSEIREntitiesConn(std::string vname, epiworld_fast_uint n, epiworld_double prevalence, epiworld_double contact_rate, epiworld_double transmission_rate, epiworld_double avg_incubation_days, epiworld_double recovery_rate, std::vector&lt; epiworld_double &gt; entities, std::vector&lt; std::string &gt; entities_names, std::vector&lt; double &gt; contact_matrix)'],['../class_model_s_e_i_r_entities_conn.html#a4119bc0b631b8f41d51318b30400f217',1,'ModelSEIREntitiesConn::ModelSEIREntitiesConn(ModelSEIREntitiesConn&lt; TSeq &gt; &amp;model, std::string vname, epiworld_fast_uint n, epiworld_double prevalence, epiworld_double contact_rate, epiworld_double transmission_rate, epiworld_double avg_incubation_days, epiworld_double recovery_rate, std::vector&lt; epiworld_double &gt; entities, std::vector&lt; std::string &gt; entities_names, std::vector&lt; double &gt; contact_matrix)']]],
  ['modelsir_53',['ModelSIR',['../classepiworld_1_1epimodels_1_1_model_s_i_r.html',1,'epiworld::epimodels::ModelSIR&lt; TSeq &gt;'],['../class_model_s_i_r.html',1,'ModelSIR&lt; TSeq &gt;']]],
  ['modelsirconn_54',['ModelSIRCONN',['../classepiworld_1_1epimodels_1_1_model_s_i_r_c_o_n_n.html',1,'epiworld::epimodels::ModelSIRCONN&lt; TSeq &gt;'],['../class_model_s_i_r_c_o_n_n.html',1,'ModelSIRCONN&lt; TSeq &gt;'],['../class_model_s_i_r_c_o_n_n.html#a5b4e60e7ec41b5c94446da3306eec1d6',1,'ModelSIRCONN::ModelSIRCONN()'],['../classepiworld_1_1epimodels_1_1_model_s_i_r_c_o_n_n.html#a5b4e60e7ec41b5c94446da3306eec1d6',1,'epiworld::epimodels::ModelSIRCONN::ModelSIRCONN()']]],
  ['modelsird_55',['ModelSIRD',['../classepiworld_1_1epimodels_1_1_model_s_i_r_d.html',1,'epiworld::epimodels::ModelSIRD&lt; TSeq &gt;'],['../class_model_s_i_r_d.html',1,'ModelSIRD&lt; TSeq &gt;'],['../classepiworld_1_1epimodels_1_1_model_s_i_r_d.html#a92cab572b7f648ee192aa38614f21bbf',1,'epiworld::epimodels::ModelSIRD::ModelSIRD()'],['../class_model_s_i_r_d.html#a92cab572b7f648ee192aa38614f21bbf',1,'ModelSIRD::ModelSIRD()']]],
  ['modelsirdconn_56',['ModelSIRDCONN',['../classepiworld_1_1epimodels_1_1_model_s_i_r_d_c_o_n_n.html',1,'epiworld::epimodels::ModelSIRDCONN&lt; TSeq &gt;'],['../class_model_s_i_r_d_c_o_n_n.html',1,'ModelSIRDCONN&lt; TSeq &gt;'],['../class_model_s_i_r_d_c_o_n_n.html#a66f1100d3a040a638782b45a28a970af',1,'ModelSIRDCONN::ModelSIRDCONN()'],['../classepiworld_1_1epimodels_1_1_model_s_i_r_d_c_o_n_n.html#a66f1100d3a040a638782b45a28a970af',1,'epiworld::epimodels::ModelSIRDCONN::ModelSIRDCONN()']]],
  ['modelsirlogit_57',['ModelSIRLogit',['../classepiworld_1_1epimodels_1_1_model_s_i_r_logit.html',1,'epiworld::epimodels::ModelSIRLogit&lt; TSeq &gt;'],['../classepiworld_1_1epimodels_1_1_model_s_i_r_logit.html#ac2529763b3f72163846c88d2985a57fc',1,'epiworld::epimodels::ModelSIRLogit::ModelSIRLogit()'],['../class_model_s_i_r_logit.html#ac2529763b3f72163846c88d2985a57fc',1,'ModelSIRLogit::ModelSIRLogit()'],['../class_model_s_i_r_logit.html',1,'ModelSIRLogit&lt; TSeq &gt;']]],
  ['modelsis_58',['ModelSIS',['../classepiworld_1_1epimodels_1_1_model_s_i_s.html',1,'epiworld::epimodels::ModelSIS&lt; TSeq &gt;'],['../class_model_s_i_s.html',1,'ModelSIS&lt; TSeq &gt;']]],
  ['modelsisd_59',['ModelSISD',['../classepiworld_1_1epimodels_1_1_model_s_i_s_d.html',1,'epiworld::epimodels::ModelSISD&lt; TSeq &gt;'],['../class_model_s_i_s_d.html',1,'ModelSISD&lt; TSeq &gt;']]],
  ['modelsurv_60',['ModelSURV',['../classepiworld_1_1epimodels_1_1_model_s_u_r_v.html',1,'epiworld::epimodels::ModelSURV&lt; TSeq &gt;'],['../class_model_s_u_r_v.html',1,'ModelSURV&lt; TSeq &gt;']]]
];
